---
title: "Data frames"
author: "WOONS"
date: "2016년 8월 14일"
output: html_document
---

---

**데이터프레임이란**
```{r}
# Print out built-in R data frame
mtcars 

# Call head() on mtcars
head(mtcars)

# Investigate the structure of mtcars
str(mtcars)
```

**데이터프레임 만들기**
```{r}
# Definition of vectors
name <- c("Mercury", "Venus", "Earth", "Mars", "Jupiter", "Saturn", "Uranus", "Neptune")
type <- c("Terrestrial planet", "Terrestrial planet", "Terrestrial planet", 
          "Terrestrial planet", "Gas giant", "Gas giant", "Gas giant", "Gas giant")
diameter <- c(0.382, 0.949, 1, 0.532, 11.209, 9.449, 4.007, 3.883)
rotation <- c(58.64, -243.02, 1, 1.03, 0.41, 0.43, -0.72, 0.67)
rings <- c(FALSE, FALSE, FALSE, FALSE, TRUE, TRUE, TRUE, TRUE)

# Create a data frame from the vectors
planets_df <- data.frame(name, type, diameter, rotation, rings)
planets_df

# Check the structure of planets_df
str(planets_df)
```

**Selection of data frame elements**
```{r}
# The planets_df data frame from the previous exercise is pre-loaded
planets_df
# Print out diameter of Mercury (row 1, column 3)
planets_df[1,3]

# Print out data for Mars (entire fourth row)
planets_df[4,]

# The planets_df data frame from the previous exercise is pre-loaded
planets_df
# Select first 5 values of diameter column
planets_df[1:5, "diameter"]
```

**특정 칼럼만 저장하기**
```{r}
# planets_df is pre-loaded in your workspace
planets_df
# Select the rings variable from planets_df
rings_vector <- planets_df$rings
  
# Print out rings_vector
rings_vector
```

**TRUE, FALSE를 활용한 특정 칼럼 요소 출력**
```{r}
# planets_df and rings_vector are pre-loaded in your workspace
planets_df
# Adapt the code to select all columns for planets with rings
planets_df[rings_vector,]
```

**subset()를 활용한 데이터추출**
```{r}
# planets_df is pre-loaded in your workspace
planets_df
# Select planets with diameter < 1
subset(planets_df, subset = diameter < 1)
```

**Sorting your data**
```{r}
# planets_df is pre-loaded in your workspace
planets_df
# Use order() to create positions
positions <- order(planets_df$diameter)  

# Use positions to sort planets_df
planets_df[positions, ]
```


