---
title: "Matrix"
author: "WOONS"
date: "2016년 8월 14일"
output: html_document
---

---

**Matrix란**
```{r}
# 행 기준으로 3행의 메트릭스를 만들어 보기
matrix(1:9, byrow = TRUE, nrow = 3)
```

**스스로 행렬을 만들어보기**
```{r}
# Box office Star Wars (in millions!)
new_hope <- c(460.998, 314.4)
empire_strikes <- c(290.475, 247.900)
return_jedi <- c(309.306, 165.8)

# Create box_office
box_office <- c(new_hope, empire_strikes, return_jedi)
# Construct star_wars_matrix
star_wars_matrix <- matrix(box_office, byrow=TRUE, nrow = 3)
```

**Matrix 이름 할당하기**
```{r}
# Box office Star Wars (in millions!)
new_hope <- c(460.998, 314.4)
empire_strikes <- c(290.475, 247.900)
return_jedi <- c(309.306, 165.8)

# Construct matrix
star_wars_matrix <- matrix(c(new_hope, empire_strikes, return_jedi), nrow = 3, byrow = TRUE)

# Vectors region and titles, used for naming
region <- c("US", "non-US")
titles <- c("A New Hope", "The Empire Strikes Back", "Return of the Jedi")

# Name the columns with region
colnames(star_wars_matrix) <- region

# Name the rows with titles
rownames(star_wars_matrix) <- titles

# Print out star_wars_matrix
star_wars_matrix
```


**Matrix의 row의 합 구하기**
```{r}
# Construct star_wars_matrix
box_office <- c(460.998, 314.4, 290.475, 247.900, 309.306, 165.8)
star_wars_matrix <- matrix(box_office, nrow = 3, byrow = TRUE,
                           dimnames = list(c("A New Hope", "The Empire Strikes Back", "Return of the Jedi"), 
                                           c("US", "non-US")))

# Calculate worldwide box office figures
worldwide_vector <- rowSums(star_wars_matrix)
worldwide_vector
```

**칼럼(column)추가하기, cbind()활용**
```{r}
# Construct star_wars_matrix
box_office <- c(460.998, 314.4, 290.475, 247.900, 309.306, 165.8)
star_wars_matrix <- matrix(box_office, nrow = 3, byrow = TRUE,
                           dimnames = list(c("A New Hope", "The Empire Strikes Back", "Return of the Jedi"), 
                                           c("US", "non-US")))

# The worldwide box office figures
worldwide_vector <- rowSums(star_wars_matrix)

# Bind the new variable worldwide_vector as a column to star_wars_matrix
all_wars_matrix <- cbind(star_wars_matrix, worldwide_vector)
```

**열(row)추가하기, rbind()활용**
```{r}
# star_wars_matrix and star_wars_matrix2 are available in your workspace
star_wars_matrix

a <- c(474.5, 552.5)
b <- c(310.7, 338.7)
c <- c(380.3, 468.5)
d <- c(a, b, c)

star_wars_matrix2 <- matrix(d, byrow = TRUE, nrow = 3)
colnames(star_wars_matrix2) <- c("US", "non-US")
rownames(star_wars_matrix2) <- c("The Phantom Menace", "Attack of the Clones", "Revenge of the Sith")
star_wars_matrix2

# Combine both Star Wars trilogies in one matrix
all_wars_matrix <- rbind(star_wars_matrix, star_wars_matrix2) 
```

**열의 합계를 구해보자**
```{r}
# all_wars_matrix is available in your workspace
all_wars_matrix

# Total revenue for US and non-US
total_revenue_vector <- colSums(all_wars_matrix)
 
# Print out total_revenue_vector

total_revenue_vector
```

**Matirx의 개별 요소 선택하기**
```{r}
# all_wars_matrix is available in your workspace
all_wars_matrix

# Select the non-US revenue for all movies
non_us_all <- all_wars_matrix[,2]

# Average non-US revenue
mean(non_us_all)
  
# Select the non-US revenue for first two movies
non_us_some <- all_wars_matrix[1:2, 2]
  
# Average non-US revenue for first two movies
mean(non_us_some)
```

**Matrix의 연산**
```{r}
# all_wars_matrix and ticket_prices_matrix are available in your workspace
all_wars_matrix

d1 <- c(5.0, 5.0)
d2 <- c(6.0, 6.0)
d3 <- c(7.0, 7.0)
d4 <- c(4.0, 4.0)
d5 <- c(4.5, 4.5)
d6 <- c(4.9, 4.9)
d_total <- c(d1, d2, d3, d4, d5, d6)

ticket_prices_matrix <- matrix(d_total, byrow = TRUE, ncol = 2)
colnames(ticket_prices_matrix) <- c("US", "non-US")
rownames(ticket_prices_matrix) <- c("A New Hope", "The Empire Strikes Back", "Return of the Jedi", "The Phantom Menace", "Attack of the Clones", "Revenge of the Sith")
# Estimated number of visitors
visitors <- all_wars_matrix / ticket_prices_matrix
visitors
# US visitors
us_visitors <- visitors[,1]

# Average number of US visitors
mean(us_visitors)
```

